# You can you minimessage in the prefix field, usage - https://docs.advntr.dev/minimessage/format.html#standard-tags

enabled: true

# Toggle for update checker messages
update_checker: true

# Plugin's system messages prefix
prefix: "<gradient:#5e4fa2:#f79459>VelocityCoolList</gradient> <red><bold>>>></red>"

# Toggle for the clear command
enable_clear_command: false

# Do not touch
config_version: 2